### ISSUE TITLE
fix: ensure correct IP address will used

### ISSUE THREAD

**Issue by fty4** [taskmedia/ddns-whitelist#19]
Currently with [k3s](https://k3s.io/) the IP address does not match the one from the requester but from the internal network (`10.42.0.1`).
This will result that `X-Forwarded-For`, `X-Real-Ip` will not help to whitelist and block the access.

**Comment by fty4** [comment]
This problem occurs when the `externalTrafficPolicy` is set to `Cluster` and not `Local`.

Helm chart value needs changes as follows:

```yaml
service:
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: "1.2.3.4" # your IP (optional)
```

---

also see:
- https://www.reddit.com/r/kubernetes/comments/sue2yh/comment/hxafy3v/
- [traefik/traefik-helm-chart:/traefik/values.yaml](https://github.com/traefik/traefik-helm-chart/blob/ed4c1632412a745c77124f78fb033c79194d075b/traefik/values.yaml#L745-L747)
